version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "RumenDamyanov"
    assignees:
      - "RumenDamyanov"
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group patch updates together
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "RumenDamyanov"
    assignees:
      - "RumenDamyanov"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"