name: Style

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  style:
    name: Code Style Check
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            dependencies-php-8.2-composer-
            dependencies-php-

      - name: Install Composer dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Check coding standards
        run: |
          # Show all issues (warnings and errors) for information
          echo "::group::PHPCS Report (including warnings)"
          ./vendor/bin/phpcs --standard=phpcs.xml src tests || true
          echo "::endgroup::"

          # Fail only on actual errors (not warnings)
          echo "::group::Checking for errors only"
          ./vendor/bin/phpcs --standard=phpcs.xml --error-severity=1 --warning-severity=0 src tests
          echo "::endgroup::"